# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

array_w_mean <- function(array, df) {
    .Call('_slabR_array_w_mean', PACKAGE = 'slabR', array, df)
}

